- name: ホストネームを設定
  hostname: name={{ hostname }}
  tags: common

- name: グループを追加
  group: name={{ user_group }}
  tags: common

- name: ユーザーを追加
  user: name={{ user_name }} group={{ user_group }}
  tags: common

# - name: ユーザにsudo権限を付与
#   lineinfile:
#     dest: /etc/sudoers
#     backup: yes
#     line: '{{ user_name }} ALL=(ALL) ALL'
#   tags: common