<?php

acf_add_local_field_group(array (
  'key' => 'group_598a9cddd60c5',
  'title' => 'COLOR',
  'fields' => array (
    array (
      'key' => 'field_598a9d0ad5a2b',
      'label' => 'カラーセット',
      'name' => 'colorset',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => '',
      'layout' => 'row',
      'button_label' => '行を追加',
      'sub_fields' => array (
        array (
          'key' => 'field_598a9f8d21d1a',
          'label' => 'ラベル',
          'name' => 'label',
          'type' => 'text',
          'instructions' => '',
          'required' => '',
          'conditional_logic' => '',
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'prepend' => '',
          'append' => '',
          'maxlength' => '',
          'readonly' => 0,
          'disabled' => 0,
        ),
        array (
          'key' => 'field_598a9d20d5a2c',
          'label' => 'ベースカラー（薄色）',
          'name' => 'base',
          'type' => 'color_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
        ),
        array (
          'key' => 'field_598a9d70d5a2d',
          'label' => 'フォントカラー（濃色）',
          'name' => 'font',
          'type' => 'color_picker',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
        ),
      ),
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'colorset',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));