<?php

acf_add_local_field_group(array (
  'key' => 'group_59897725310f8',
  'title' => 'PICK UP',
  'fields' => array (
    array (
      'key' => 'field_598aa106065d6',
      'label' => '特集',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_598aa113065d7',
      'label' => '特集',
      'name' => 'pickup_feature',
      'type' => 'taxonomy',
      'instructions' => 'トップページのメインエリアに表示されます。
この特集のカラーがサイト全体のカラーとなります。',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'feature',
      'field_type' => 'radio',
      'allow_null' => 0,
      'add_term' => 1,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'object',
      'multiple' => 0,
    ),
    array (
      'key' => 'field_599a7e7ea6a69',
      'label' => 'グロナビ',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_599a7e42a6a68',
      'label' => 'グロナビ表示タグ',
      'name' => 'pickup_tags',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'post_tag',
      'field_type' => 'checkbox',
      'allow_null' => 0,
      'add_term' => 1,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'object',
      'multiple' => 0,
    ),
    array (
      'key' => 'field_59b68fda6ee1b',
      'label' => 'グロナビ表示カテゴリー',
      'name' => 'pickup_category',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'category',
      'field_type' => 'checkbox',
      'allow_null' => 0,
      'add_term' => 1,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'object',
      'multiple' => 0,
    ),
    array (
      'key' => 'field_599a7ebba6a6a',
      'label' => 'グロナビ表示連載',
      'name' => 'pickup_series',
      'type' => 'taxonomy',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'taxonomy' => 'series',
      'field_type' => 'checkbox',
      'allow_null' => 0,
      'add_term' => 1,
      'save_terms' => 0,
      'load_terms' => 0,
      'return_format' => 'object',
      'multiple' => 0,
    ),
    array (
      'key' => 'field_5989772b4c766',
      'label' => 'GIRLFRIEND',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_5989774b4c767',
      'label' => 'GIRLFRIEND',
      'name' => 'pickup_girlfriends',
      'type' => 'repeater',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'collapsed' => '',
      'min' => '',
      'max' => 4,
      'layout' => 'row',
      'button_label' => '行を追加',
      'sub_fields' => array (
        array (
          'key' => 'field_598977634c768',
          'label' => 'GIRLFRIEND',
          'name' => 'tx_girlfriend',
          'type' => 'taxonomy',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'taxonomy' => 'girlfriend',
          'field_type' => 'radio',
          'allow_null' => 0,
          'add_term' => 1,
          'save_terms' => 0,
          'load_terms' => 0,
          'return_format' => 'object',
          'multiple' => 0,
        ),
        array (
          'key' => 'field_598977a84c769',
          'label' => 'コメント',
          'name' => 'comment',
          'type' => 'textarea',
          'instructions' => '',
          'required' => 0,
          'conditional_logic' => 0,
          'wrapper' => array (
            'width' => '',
            'class' => '',
            'id' => '',
          ),
          'default_value' => '',
          'placeholder' => '',
          'maxlength' => '',
          'rows' => '',
          'new_lines' => 'br',
          'readonly' => 0,
          'disabled' => 0,
        ),
      ),
    ),
    array (
      'key' => 'field_598aa170065db',
      'label' => 'トップページPICKUPエリア',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_598aa142065da',
      'label' => 'トップページPICKUPエリア',
      'name' => 'pickup_post',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'post',
      ),
      'taxonomy' => array (
      ),
      'filters' => array (
        0 => 'search',
        1 => 'post_type',
        2 => 'taxonomy',
      ),
      'elements' => '',
      'min' => '',
      'max' => 1,
      'return_format' => 'object',
    ),
    array (
      'key' => 'field_599e48b89941c',
      'label' => 'RECOMMEND',
      'name' => '',
      'type' => 'tab',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'placement' => 'top',
      'endpoint' => 0,
    ),
    array (
      'key' => 'field_599e48950085b',
      'label' => 'RECOMMEND',
      'name' => 'recommend_post',
      'type' => 'relationship',
      'instructions' => '',
      'required' => 0,
      'conditional_logic' => 0,
      'wrapper' => array (
        'width' => '',
        'class' => '',
        'id' => '',
      ),
      'post_type' => array (
        0 => 'post',
      ),
      'taxonomy' => array (
      ),
      'filters' => array (
        0 => 'search',
        1 => 'post_type',
        2 => 'taxonomy',
      ),
      'elements' => '',
      'min' => '',
      'max' => '',
      'return_format' => 'object',
    ),
  ),
  'location' => array (
    array (
      array (
        'param' => 'options_page',
        'operator' => '==',
        'value' => 'pickup',
      ),
    ),
  ),
  'menu_order' => 0,
  'position' => 'normal',
  'style' => 'default',
  'label_placement' => 'top',
  'instruction_placement' => 'label',
  'hide_on_screen' => '',
  'active' => 1,
  'description' => '',
));